pipeline {
    agent any

    tools {
        maven 'Maven3' // configure Maven installation in Jenkins global tools
        jdk 'Java24'   // configure JDK in Jenkins global tools
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'rasiga', url: 'https://github.com/Sowmiya05-SK/Naan-mudhalvan--Devops.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean test package'
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }

        stage('Optional: Docker Build') {
            steps {
                script {
                    if(fileExists('Dockerfile')) {
                        sh 'docker build -t hcms-complaint-ui:${BUILD_NUMBER} .'
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
